# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-12 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lgzp',
            new_name='lgzp1',
        ),
    ]
